"""add_battery_and_wifi_fields

Revision ID: 3754e64ea8d2
Revises: 5ec51b9da40d
Create Date: 2026-04-27 18:24:16.163127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3754e64ea8d2'
down_revision: Union[str, None] = '5ec51b9da40d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('battery_voltage', sa.Float(), nullable=True))
    op.add_column('sensor_readings', sa.Column('battery_pct', sa.Integer(), nullable=True))
    op.add_column('sensor_readings', sa.Column('wifi_rssi', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'wifi_rssi')
    op.drop_column('sensor_readings', 'battery_pct')
    op.drop_column('sensor_readings', 'battery_voltage')
    # ### end Alembic commands ###
