"""add_command_queue

Revision ID: 5ec51b9da40d
Revises: decf1dfce8f6
Create Date: 2026-04-23 00:07:24.378022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec51b9da40d'
down_revision: Union[str, None] = 'decf1dfce8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('cmd', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKED', name='commandstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_queue_device_id'), 'command_queue', ['device_id'], unique=False)
    op.create_index(op.f('ix_command_queue_status'), 'command_queue', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_queue_status'), table_name='command_queue')
    op.drop_index(op.f('ix_command_queue_device_id'), table_name='command_queue')
    op.drop_table('command_queue')
    # ### end Alembic commands ###
