"""Add soil moisture to reading

Revision ID: decf1dfce8f6
Revises: eac82c4462f9
Create Date: 2026-04-22 10:41:43.816017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'decf1dfce8f6'
down_revision: Union[str, None] = 'eac82c4462f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('soil_moisture', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'soil_moisture')
    # ### end Alembic commands ###
