"""Add soil moisture threshold

Revision ID: eac82c4462f9
Revises: 0001
Create Date: 2026-04-22 10:33:39.226292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac82c4462f9'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plant_profiles', sa.Column('soil_moisture_min', sa.Float(), nullable=False, server_default='20.0'))
    op.add_column('plant_profiles', sa.Column('soil_moisture_max', sa.Float(), nullable=False, server_default='80.0'))
    op.drop_constraint('plant_profiles_device_id_key', 'plant_profiles', type_='unique')
    op.drop_index('ix_plant_profiles_device_id', table_name='plant_profiles')
    op.create_index(op.f('ix_plant_profiles_device_id'), 'plant_profiles', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plant_profiles_device_id'), table_name='plant_profiles')
    op.create_index('ix_plant_profiles_device_id', 'plant_profiles', ['device_id'], unique=False)
    op.create_unique_constraint('plant_profiles_device_id_key', 'plant_profiles', ['device_id'])
    op.drop_column('plant_profiles', 'soil_moisture_max')
    op.drop_column('plant_profiles', 'soil_moisture_min')
    # ### end Alembic commands ###
